# Generated by Django 3.2.4 on 2021-06-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='image',
            new_name='img',
        ),
    ]
