# Generated by Django 3.2.4 on 2021-06-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentapp', '0003_rename_image_doctor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, upload_to='department'),
        ),
    ]
